openapi: 3.0.0
info:
  description: This API provides audit info
  version: "1.0.0"
  title: Train Travelers Audit API
  contact:
    email: tiyer@my.bcit.ca
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /route/schedule:
    get:
      summary: gets a train route reading from history
      operationId: app.get_train_route_reading
      description: Gets train route schedule from the event store
      parameters:
        - name: index
          in: query
          description: Gets the train route at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        "200":
          description: Successfully returned a train route event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/TrainRoute"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Message404"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Message404"
  /route/ticket:
    get:
      summary: gets a ticket booking from history
      operationId: app.get_ticket_booking_reading
      description: Gets train ticket booking from the event store
      parameters:
        - name: index
          in: query
          description: Gets the ticket booking at the index in the event store
          schema:
            type: integer
            example: 100
      responses:
        "200":
          description: Successfully returned a ticket booking event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/TicketBooking"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Message404"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Message404"
components:
  schemas:
    TrainRoute:
      type: object
      required:
        - route_id
        - train_line
        - route_origin
        - route_destination
        - route_departure_time
        - estimated_travel_time
      properties:
        route_id:
          type: integer
          example: 32
        train_line:
          type: string
          example: CNRail
        route_origin:
          type: string
          example: Rotterdam
        route_destination:
          type: string
          example: Paris
        route_departure_time:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
        estimated_travel_time:
          type: integer
          example: 2
    TicketBooking:
      type: object
      required:
        - ticket_id
        - cabin_class
        - customer_name
        - customer_email
        - route_id
      properties:
        ticket_id:
          type: integer
          example: 32
        cabin_class:
          type: string
          example: Economy
        customer_name:
          type: string
          example: Taz Forster
        customer_email:
          type: string
          example: "tf@mail.me"
        route_id:
          type: integer
          example: 33
    Message404:
      type: object
      properties:
        message:
          type: string
